name: 'Build and Push Docker'
description: 'Builds and pushes Docker images to a registry'
inputs:
  dockerfile_path:
    description: 'path to the Dockerfile'
    required: true
  build_args:
    description: 'build arguments for Docker'
    required: false
  context:
    description: 'build context for Docker'
    required: false
    default: .
  push:
    description: 'whether to push the image'
    required: false
    default: 'true'
  platforms:
    description: 'platforms for Docker Buildx'
    default: 'linux/amd64'
  lables:
    description: 'lables for Docker Buildx'
    required: false
  cache-from: 
    description: 'cache-from for Docker Buildx'
    required: false
  cache-to: 
    description: 'cache-to for Docker Buildx'
    required: false
  registry:
    description: 'Container registry (Optional). '
    required: false
  dockerhub_username:
    description: 'DockerHub Username'
    required: true
  dockerhub_token:
    description: 'DockerHub Token'
    required: true

  
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    # - name: Log in to ghcr.io
    #   uses: docker/login-action@v3.0.0
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5.1.0
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile_path }}
        tags: ${{ inputs.image_name }}
        build-args: ${{ inputs.build_args }}
        push: ${{ inputs.push }}
        platforms: ${{ inputs.platforms }}
        labels: ${{ inputs.labels }}
        cache-from: ${{ inputs.cache-from }}
        cache-to: ${{ inputs.cache-to }}
