name: 'Build and Push Docker'
description: 'Builds and pushes Docker images to a registry'
inputs:
  image_name:
    description: 'Docker image name'
    required: true
  dockerfile_path:
    description: 'Path to the Dockerfile'
    required: true
  build_args:
    description: 'Build arguments for Docker'
    required: false
  push:
    description: 'Whether to push the image'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Log in to DockerHub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ${{ inputs.dockerfile_path }}
        tags: ${{ inputs.image_name }}
        build-args: ${{ inputs.build_args }}
        push: ${{ inputs.push }}
