server:
  # Port
  port: 9201
  servlet:
    context-path: /v1/server/center

# application-prod.yml
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: blossom.project.towelove.msg.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Use local xxl-job
# xxl:
#  job:
#    # Scheduling center deployment root address
#    admin:
#      addresses: http://localhost:17777/xxl-job-admin  # Scheduling center address, used for executor heartbeat registration and task result callback
#    # Executor communication TOKEN
#    accessToken: towelove # Enable when not empty, used for secure communication between the executor and the scheduling center
#    # Executor configuration
#    executor:
#      appname: towelove-msg  # Executor AppName, used for heartbeat registration grouping
#      address:  # Executor registration address, prioritized as the primary registration address
#      ip:  # Executor IP, manually set a specific IP when there are multiple network cards
#      port: 9999  # Executor port number, default is 9999, different ports should be configured for multiple executors on a single machine
#      logpath: D:\desktop\Towelove\logs  # Path to store executor running log files
#      logretentiondays: 30  # Number of days to keep executor log files, expired logs are automatically cleaned up