# Tomcat
server:
  port: 8080
spring:
  application:
    # Application name
    name: towelove-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # Set to true to make custom filters ineffective, only Global filters will be effective
      routes:
        # towelove-user module path configuration
        - id: towelove-user
          uri: lb://towelove-user
          predicates:
            - Path=/v1/user/**
        # towelove-auth module path configuration
        - id: towelove-auth
          uri: lb://towelove-auth
          predicates:
            - Path=/v1/auth/**
        # towelove-msg module path configuration
        - id: towelove-msg
          uri: lb://towelove-msg
          predicates:
            - Path=/v1/msg/**
        # towelove-loves module path configuration
        - id: towelove-loves
          uri: lb://towelove-loves
          predicates:
            - Path=/v1/loves/**
        # towelove-server-center module path configuration
        - id: towelove-server-center
          uri: lb://towelove-server-center
          predicates:
            - Path=/v1/server/center/**

sa-token:
  # Token name (also the cookie name)
  token-name: Authorization
  # Token expiration time (in seconds) Default is 30 days, -1 represents permanent validity
  timeout: 259200
  # Token minimum activity frequency (in seconds), if the token is not accessed for more than this time, it will be frozen. Default is -1, which means no restriction, never frozen.
  active-timeout: 43200
  # Whether to allow concurrent logins for the same account (true allows concurrent logins, false allows only one login at a time)
  is-concurrent: false
  # When multiple users log in to the same account, should they share the same token (true means all logins share one token, false means a new token is created for each login)
  is-share: true
  # Token style
  token-style: uuid
  # Whether to output operation logs
  is-log: true
