# Tomcat
server:
  port: 8080
spring:
  application:
    # 应用名称
    name: towelove-gateway
  profiles:
    # 环境配置
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # 设定为true 会导致自定义的filter失效 只有Global的有效
      routes:
        - id: towelove-user
          uri: lb://towelove-user
          predicates:
            - Path=/v1/user/**
        #          filters:
        #            # 具体微服务限流位置
        #            - name: RequestRateLimiter  #请求数限流 名字不能随便写
        #              args:
        #                key-resolver: "#{@ipKeyResolver}"  #指定限流的key
        #                redis-rate-limiter.replenishRate: 1 # 允许每秒处理了多少个请求
        #                redis-rate-limiter.burstCapacity: 1 # 令牌桶的容量（最高处理并发容量大小1）
        - id: towelove-auth
          uri: lb://towelove-auth
          predicates:
            - Path=/v1/auth/**
        - id: towelove-msg
          uri: lb://towelove-msg
          predicates:
            - Path=/v1/msg/**
        - id: towelove-loves
          uri: lb://towelove-loves
          predicates:
            - Path=/v1/loves/**
        - id: towelove-server-center
          uri: lb://towelove-server-center
          predicates:
            - Path=/v1/server/center/**


sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true