# Tomcat
# remember to update this yml
server:
  port: 9206
  servlet:
    context-path: /v1/community
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: blossom.project.towelove.user.domain
spring:
  profiles:
    active: @activeProperties@


  main:
    allow-bean-definition-overriding: true