server:
  # Port
  port: 9204
  servlet:
    context-path: /v1/auth
############## Sa-Token Configuration (Documentation: https://sa-token.cc)  ##############

sa-token:
  # Token name (also the cookie name)
  token-name: Authorization
  # Token expiration time (in seconds) Default is 30 days, -1 represents permanent validity
  timeout: 2592000
  # Token minimum activity frequency (in seconds), if the token is not accessed for more than this time, it will be frozen. Default is -1, which means no restriction, never frozen.
  active-timeout: -1
  # Whether to allow concurrent logins for the same account (true allows concurrent logins, false allows only one login at a time)
  is-concurrent: true
  # When multiple users log in to the same account, should they share the same token (true means all logins share one token, false means a new token is created for each login)
  is-share: true
  # Token style
  token-style: uuid
  # Whether to output operation logs
  is-log: true