
name: Build And Deploy to Docker Hub

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  # pull_request:
  #   branches:
  #     - 'master'
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag for the Docker image (semver)"
        required: true

env:
  UNIQUE_TAG: ${{ github.sha }}

jobs:
  # Build-All-Java-Package
  Build-And-Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: 'gateway'
            jarName: 'Towelove-Gateway'
          - service: 'auth'
            jarName: 'Towelove-Auth'
          - service: 'user'
            jarName: 'Towelove-User'
          - service: 'loves'
            jarName: 'Towelove-Loves'
          - service: 'msg'
            jarName: 'Towelove-Msg'
          - service: 'server-center'
            jarName: 'Towelove-Server-Center'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  
    - name: Generate short SHA
      id: shortsha
      run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_OUTPUT
    - name: Set up JDK 17 
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Create Maven settings.xml with Repositories
      run: |
        cat <<EOF > ${{ github.workspace }}/settings.xml
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <localRepository/>
          <interactiveMode/>
          <usePluginRegistry/>
          <offline/>
          <pluginGroups/>
          <servers/>
          <mirrors/>
          <proxies/>
          <profiles>
            <profile>
              <id>extra-repos</id>
              <repositories>
                <!-- Google's Maven repository -->
                <repository>
                  <id>google</id>
                  <url>https://maven.google.com/</url>
                  <releases><enabled>true</enabled></releases>
                  <snapshots><enabled>true</enabled></snapshots>
                </repository>
              </repositories>
            </profile>
          </profiles>
          <activeProfiles>
            <activeProfile>extra-repos</activeProfile>
          </activeProfiles>
        </settings>
        EOF
    - name: Build with Maven
      run: mvn clean  -B package --file pom.xml -DskipTests -P pro --settings ./settings.xml
    - name: Copy Artifacts
      run: |
        mkdir staging && cp Towelove-*/target/*.jar staging
        ls -al staging
    - name: Set up Docker Meta
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: |
          towelove/towelove-${{ matrix.service }}
        tags: |
          type=raw,value=0.1.0-${{ steps.shortsha.outputs.SHORT_SHA }}
          type=semver,pattern={{version}}${{ github.event_name == 'workflow_dispatch' && format(',value={0}', github.event.inputs.version) || '' }}
          type=semver,pattern={{major}}.{{minor}}${{ github.event_name == 'workflow_dispatch' && format(',value={0}', github.event.inputs.version) || '' }}
# TODO 更新tag规则          
#type=ref,event=branch
    - name: Build and push Docker image
      uses: ./.github/actions/build-and-push-docker
      with:
        dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
        context: .
        file: ./Docker-Build/Dockerfile
        build-args: SERVICE_NAME=${{ matrix.jarName }}
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: SSH Deploy
      uses: falling42/ssh-deploy@v0.1.10
      with:
        use_screen: 'yes'
        use_jump_host: 'yes'
        jump_ssh_host: ${{ secrets.JUMP_SSH_HOST }}
        jump_ssh_user: ${{ secrets.JUMP_SSH_USER }}
        jump_ssh_private_key: ${{ secrets.JUMP_SSH_PRIVATE_KEY }}
        ssh_host: ${{ secrets.SSH_HOST }}
        ssh_user: ${{ secrets.SSH_USER }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        execute_remote_script: 'yes'
        deploy_script: '/opt/ops/deploy.sh'
        service_name: ${{ matrix.jarName }}
        service_version: ${{ steps.meta.outputs.version }}